import{a as y,i as n,S as b}from"./assets/vendor-b0d10f48.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const L="43963855-b23ab28bc2f72f8207f09d24a",P="https://pixabay.com/api/",w=15;y.defaults.baseURL=P;const E=async(t,r=1)=>{try{const{data:o}=await y.get("",{params:{key:L,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:w,page:r}});return o}catch(o){console.log(o)}};function S(t){return t.map(({webformatURL:r,largeImageURL:o,tags:a,likes:e,views:s,comments:l,downloads:p})=>`<li class="gallery-item">
            <a class="gallery-link" href="${o}">
              <img class="gallery-img" src="${r}" alt="${a}" />
            </a>
            <div class="small-info">
             <small class="text-body-likes">Likes: ${e}</small>
             <small class="text-body-views">Views: ${s}</small>
             <small class="text-body-comments">Comments: ${l}</small>
             <small class="text-body-downloads">Downloads: ${p}</small>
            </div>
          </li>`).join("")}const v=document.querySelector(".search-form"),f=document.querySelector(".gallery-list"),u=document.querySelector(".loader"),d=document.querySelector(".btn-load"),q=15;let m="",i=1,h=0,c;const x=()=>{const t=document.querySelectorAll(".gallery-list li");if(t.length>0){const a=t[t.length-1].getBoundingClientRect().height*2;window.scrollBy({top:a,left:0,behavior:"smooth"})}};async function g(t,r){try{const o=await E(t,r);if(o.hits.length===0)n.show({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});else{const a=S(o.hits);f.insertAdjacentHTML("beforeend",a),c?c.refresh():c=new b(".gallery-list a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250,className:"my-custom-lightbox"}),h=Math.ceil(o.totalHits/q),h>i?d.classList.remove("is-hidden"):(d.classList.add("is-hidden"),n.show({title:"Info",color:"green",message:"We're sorry, but you've reached the end of search results."})),x()}}catch{n.show({title:"Error",color:"red",message:"Sorry, there was an error fetching images. Please try again later."})}finally{u.classList.add("is-hidden")}}async function M(t){t.preventDefault();const r=t.target.querySelector(".form-input").value.trim();if(r===""){n.show({title:"Error",color:"red",message:"Sorry, there was an error fetching images. Please try again later."});return}f.innerHTML="",m=r,i=1,u.classList.remove("is-hidden"),await g(m,i),t.target.reset()}async function $(){i+=1,u.classList.remove("is-hidden"),await g(m,i)}v.addEventListener("submit",M);d.addEventListener("click",$);
//# sourceMappingURL=commonHelpers.js.map
